### ISSUE TITLE
Automated Testing Sim Error (9/28/2016 9:30 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#227]
```
Error: Assertion failed: not namespaced: gravityAndOrbits.GAOBodiesEnum
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at http://phettest.colorado.edu/joist/js/checkNamespaces.js?bust=1475078332951:78:17
    at visit (http://phettest.colorado.edu/joist/js/checkNamespaces.js?bust=1475078332951:63:11)
    at checkNamespaces (http://phettest.colorado.edu/joist/js/checkNamespaces.js?bust=1475078332951:77:5)
    at Object.launch (http://phettest.colorado.edu/joist/js/SimLauncher.js?bust=1475078332951:132:17)
    at http://phettest.colorado.edu/gravity-and-orbits/js/gravity-and-orbits-main.js?bust=1475078332951:34:15
    at Object.execCb (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.check (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:866:35)
    at Object. (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1113:20)
    at http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:132:17
```

**Comment by jessegreenberg** [comment]
Thanks @phet-steele.
