### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#326]
```
gravity-and-orbits : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589522260863%7D&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:301:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589530675751%7D&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:301:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/mirror-inputs/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589521614779%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:301:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/mirror-inputs/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589530031726%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:301:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589521655367%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:301:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589532079176%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:301:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/studio/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589521684338%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
gravityAndOrbits.modelScreen.model.timeControlSpeedProperty: 7. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
gravityAndOrbits.modelScreen.model.timeControlSpeedProperty: 7. Any schema entries in the overrides file must exist in the baseline file.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:357:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:305:16)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/studio/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589517262669%22%2C%22timestamp%22%3A1589532881150%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
gravityAndOrbits.modelScreen.model.timeControlSpeedProperty: 7. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
gravityAndOrbits.modelScreen.model.timeControlSpeedProperty: 7. Any schema entries in the overrides file must exist in the baseline file.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:357:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:305:16)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/tandem/js/phetioAPIValidation.js:105:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io/js/phetioEngine.js:175:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:270:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:170:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/axon/js/Property.js:340:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/joist/js/Sim.js:859:57
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-and-orbits&phetioDebug
75 out of 77 tests passed. 2 failed.
SimTests: gravity-and-orbits: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/js/tests/SimTests.js:321

SimTests: gravity-and-orbits: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/js/tests/SimTests.js:415

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM

----------------------------------

gravity-and-orbits : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-and-orbits
75 out of 77 tests passed. 2 failed.
SimTests: gravity-and-orbits: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/js/tests/SimTests.js:321

SimTests: gravity-and-orbits: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: gravityAndOrbits.modelScreen.model.timeControlSpeedProperty
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589517262669/phet-io-wrappers/js/tests/SimTests.js:415

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 5/14/2020, 10:34:22 PM
```

**Comment by samreid** [comment]
This has been clear for a while, closing.
