### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#408]
```
gravity-and-orbits : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 52355ms
Building runnable repository (gravity-and-orbits, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 7156ms
>> Unused string: key=gravity-and-orbits.title, value=Gravity and Orbits
>> Unused string: key=earthMasses, value=Earth masses
>> Unused string: key=planet, value=Planet
>> Unused string: key=planetMass, value=Planet Mass
>> Unused string: key=velocity, value=Velocity
>> Unused string: key=measuringTape, value=Measuring Tape
>> Unused string: key=billionBillionSpaceStationMasses, value=billion billion Space Station masses
>> Unused string: key=spaceStationMass, value=Space Station Mass
>> Unused string: key=gravityForce, value=Gravity Force
>> Unused string: key=model, value=Model
>> Unused string: key=moon, value=Moon
>> Unused string: key=moonMass, value=Moon Mass
>> Unused string: key=thousandEarthMasses, value=thousand Earth masses
>> Unused string: key=on, value=on
>> Unused string: key=kilometers, value=kilometers
>> Unused string: key=clear, value=Clear
>> Unused string: key=satellite, value=Satellite
>> Unused string: key=satelliteMass, value=Satellite Mass
>> Unused string: key=gravity, value=Gravity:
>> Unused string: key=grid, value=Grid
>> Unused string: key=mass, value=Mass
>> Unused string: key=off, value=off
>> Unused string: key=path, value=Path
>> Unused string: key=returnObjects, value=Return Objects
>> Unused string: key=star, value=Star
>> Unused string: key=starMass, value=Star Mass
>> Unused string: key=earthMass, value=Earth mass
>> Unused string: key=toScale, value=To Scale
>> Unused string: key=v, value=V
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: missing entry for sim title, key = GRAVITY_AND_ORBITS/gravity-and-orbits.title
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1631897020141/chipper/js/grunt/buildRunnable.js:151:3)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1631897020141/chipper/js/grunt/Gruntfile.js:290:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1631897020141/chipper/js/grunt/Gruntfile.js:73:7)
Full Error details:
AssertionError [ERR_ASSERTION]: missing entry for sim title, key = GRAVITY_AND_ORBITS/gravity-and-orbits.title
Snapshot from 9/17/2021, 10:43:40 AM
```

**Comment by samreid** [comment]
Thanks, this is related to https://github.com/phetsims/chipper/issues/1053

**Comment by samreid** [comment]
Fixed, closing.
