### ISSUE TITLE
CT Designed API changes detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#409]
```
gravity-and-orbits : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1632138742661%22%2C%22timestamp%22%3A1632147132952%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

New PhET-iO Element not in reference: gravityAndOrbits.general.view.audioManager
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

New PhET-iO Element not in reference: gravityAndOrbits.general.view.audioManager
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632138742661/chipper/dist/phet-io/js/phetioEngine.js:266:35)
id: Bayes Chrome
Snapshot from 9/20/2021, 5:52:22 AM
```

**Comment by samreid** [comment]
This was introduced in https://github.com/phetsims/joist/issues/745, @zepumph should we regenerate the API?

**Comment by zepumph** [comment]
Thanks @KatieWoe, @samreid and I realized that this is because I didn't compile GAO before running `grunt generate-phet-io-api`. This will be a step that is always needed to regenerate the API for a sim that uses TS.

**Comment by samreid** [comment]
I added this to the TypeScript Quick Start guide, maybe one day we will have better tooling for this, but at least it's documented for now.  Closing.
