### ISSUE TITLE
CT myFunction is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#413]
```
gravity-and-orbits : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1635883915782%22%2C%22timestamp%22%3A1635885909649%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: myFunction is not a function
TypeError: myFunction is not a function
at getDiameter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/gravity-and-orbits/js/common/view/ExplosionNode.js:27:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/gravity-and-orbits/js/common/view/ExplosionNode.js:65:105
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/axon/js/TinyEmitter.js:65:17)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/axon/js/Property.js:230:27)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/axon/js/Property.js:152:22)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/axon/js/Property.js:294:32)
at ModelModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/gravity-and-orbits/js/common/model/GravityAndOrbitsModel.js:76:61)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/joist/js/Sim.js:240:30
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/axon/js/Action.js:171:22)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635883915782/chipper/dist/joist/js/Sim.js:722:35)
id: Bayes Chrome
Snapshot from 11/2/2021, 2:11:55 PM
```

**Comment by samreid** [comment]
The code that is failing in the stack trace is:

```js
                const myFunction = new LinearFunction(0, NUM_STEPS_FOR_ANIMATION / 2, 1, this.getMaxViewDiameter(body, modelViewTransformProperty));
                return myFunction.evaluate(numClockTicksSinceExplosion);
```

So I don't see how `TypeError: myFunction is not a function` makes any sense.  It sounds like it's reporting for a stale version where we tried to call `myFunction(...)` directly.

**Comment by samreid** [comment]
I've been fuzzing this on my side for 10 minutes and cannot see the problem (even though I see explosions).  Not sure how it is still a problem on CT even in the latest column.

**Comment by samreid** [comment]
This cleared up in later shas, closing.
