### ISSUE TITLE
CT designed api changes detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#417]
```
gravity-and-orbits : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643949881833%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:336:23)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

gravity-and-orbits : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643962765300%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:336:23)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM
```

**Comment by zepumph** [comment]
This is no longer a bug. Closing
