### ISSUE TITLE
CT: HSeparator assertion failure

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#418]
I ported HSeparator to TypeScript yesterday, and this may be related. 

```
gravity-and-orbits : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647475862143%22%2C%22timestamp%22%3A1647519746719%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/assert/js/assert.js:25:13)
at new HSeparator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/sun/js/HSeparator.js:18:15)
at new GravityAndOrbitsControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/gravity-and-orbits/js/common/view/GravityAndOrbitsControls.js:29:26)
at new GravityAndOrbitsScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/gravity-and-orbits/js/common/view/GravityAndOrbitsScreenView.js:41:26)
at ModelScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/gravity-and-orbits/js/model/ModelScreen.js:30:92)
at ModelScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/joist/js/Screen.js:210:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/joist/js/Sim.js:678:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647475862143/chipper/dist/js/joist/js/Sim.js:685:21
id: Bayes Chrome
Snapshot from 3/16/2022, 6:11:02 PM
```

**Comment by pixelzoom** [comment]
Manually mapping from .js to .ts, here's the relevant code in HSeparator:

```js
  constructor(width, providedOptions) {
    assert && assert(isFinite(width) && width > 0);
```

**Comment by pixelzoom** [comment]
I added an assertion message:

```js
  constructor( width: number, providedOptions?: HSeparatorOptions ) {
    assert && assert( isFinite( width ) && width > 0, `invalid width=${width}` );
```

**Comment by pixelzoom** [comment]
In GravityAndOrbitsControls.ts:

```js
    // top separator rectangle for the gravity control section
    const topSeparator = new HSeparator( 0, merge( { tandem: options.tandem.createTandem( 'separator1' ) }, SEPARATOR_OPTIONS ) );
    const bottomSeparator = new HSeparator( 0, merge( { tandem: options.tandem.createTandem( 'separator2' ) }, SEPARATOR_OPTIONS ) );

...
    topSeparator.setLine( 0, 0, separatorWidth, 0 );
    bottomSeparator.setLine( 0, 0, separatorWidth, 0 );
```

I'll change the assertion to `width >=0` based on this usage.

**Comment by pixelzoom** [comment]
The sim is now passing fuzz testing. Closing.
