### ISSUE TITLE
CT Designed API changes detected, please roll them back or revise the reference API:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#486]
```
gravity-and-orbits : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704714318747%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:339:22)
at addEventListener (phetioEngine.ts:326:18)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (Sim.ts:915:14)
at (Sim.ts:899:24)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at (Sim.ts:973:13)
at start (gravity-and-orbits-main.ts:52:125)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:56:42)
at forEach (asyncLoader.ts:56:21)
at proceedIfReady (asyncLoader.ts:69:11)
at image (logo_png.ts:6:0)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704709038998%2Fgravity-and-orbits%2Fgravity-and-orbits_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704714318747%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704709038998%2Fgravity-and-orbits%2Fgravity-and-orbits_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704714318747%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704714318747%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

[CONSOLE] continuous-test-load
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

id: "Sparky Node Firefox"
Snapshot from 1/8/2024, 3:17:18 AM

----------------------------------

gravity-and-orbits : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704722978267%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:339:22)
at addEventListener (phetioEngine.ts:326:18)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (Sim.ts:915:14)
at (Sim.ts:899:24)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at (Sim.ts:973:13)
at start (gravity-and-orbits-main.ts:52:125)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:56:42)
at forEach (asyncLoader.ts:56:21)
at proceedIfReady (asyncLoader.ts:69:11)
at unlockPhetioEngine (simLauncher.ts:28:6)
at then (simLauncher.ts:26:5)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704709038998%2Fgravity-and-orbits%2Fgravity-and-orbits_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704722978267%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704709038998%2Fgravity-and-orbits%2Fgravity-and-orbits_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704722978267%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704722978267%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

[CONSOLE] continuous-test-load
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

id: "Sparky Node Firefox"
Snapshot from 1/8/2024, 3:17:18 AM

----------------------------------

gravity-and-orbits : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704729588877%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:339:22)
at addEventListener (phetioEngine.ts:326:18)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (Sim.ts:915:14)
at (Sim.ts:899:24)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at (Sim.ts:973:13)
at start (gravity-and-orbits-main.ts:52:125)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:56:42)
at forEach (asyncLoader.ts:56:21)
at proceedIfReady (asyncLoader.ts:69:11)
at image (logo_png.ts:6:0)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704709038998%2Fgravity-and-orbits%2Fgravity-and-orbits_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704729588877%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704709038998%2Fgravity-and-orbits%2Fgravity-and-orbits_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704729588877%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1704709038998%22%2C%22timestamp%22%3A1704729588877%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1704709038998/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

[CONSOLE] continuous-test-load
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

gravityAndOrbits.modelScreen.model.planetMoonScene.planet.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":191129999.9999998}
actual:
{"value":191129999.99999982,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetMoonScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

gravityAndOrbits.toScaleScreen.model.starPlanetScene.star.diameterProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":"m","validValues":null,"value":1391399999.9999986}
actual:
{"value":1391399999.9999983,"validValues":null,"units":"m","numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

id: "Sparky Node Firefox"
Snapshot from 1/8/2024, 3:17:18 AM
```

**Comment by samreid** [comment]
@zepumph any ideas on this one? I'm having difficulty reproducing the problem locally or correlating with commits in the CT columns where it occurred.

**Comment by zepumph** [comment]
Tracking general issue in https://github.com/phetsims/aqua/issues/200. Caused by turning on firefox testing last week.

**Comment by zepumph** [comment]
Solved by https://github.com/phetsims/aqua/issues/200
